name: ECR Jib build and push action
description: Builds and pushes Docker images to ECR using Jib

inputs:
  ecr-lifecycle-policy:
    description: JSON lifecycle policy to apply to the ECR repo.
    required: false
  ecr-repo-name:
    description: The ECR repo name to use. If none is given, it defaults to "app/<github-repo-name>".
    required: false
  ecr-repo-policy:
    description: JSON policy to apply to the ECR repo.
    required: false
  java-distribution:
    description: The Java distribution to use. See https://github.com/actions/setup-java#supported-distributions.
    required: false
    default: temurin
  java-version:
    description: The Java version to use. See https://github.com/actions/setup-java#supported-version-syntax.
    required: false
    default: "17"
  path:
    description: The path to the pom.xml.
    required: false
    default: .
  shared-account-id:
    description: The shared account's AWS account ID.
    required: true
  shared-region:
    description: The region for the shared account.
    required: false
    default: us-east-2
  shared-role-arn:
    description: The IAM role ARN to assume in the shared account.
    required: true

outputs:
  ecr-repo-name:
    description: The ECR repo name that was created.
    value: ${{ steps.ecr-repo-name.outputs.repo-name }}

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-java@v3
    with:
      cache: 'maven'
      distribution: ${{ inputs.java-distribution }}
      java-version: ${{ inputs.java-version }}
  - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - name: Assume ECR role
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-region: ${{ inputs.shared-region }}
      role-to-assume: ${{ inputs.shared-role-arn }}
  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1
  - name: Set context
    id: context
    env:
      POMXML_PATH: ${{ inputs.path }}
      REPO: ${{ github.repository }}
      REPO_NAME: ${{ inputs.ecr-repo-name }}
      SHA: ${{ github.sha }}
    shell: bash
    run: context.sh
  - name: Create ECR repo
    uses: byerobot/create-ecr-repository-action@v1
    id: create-ecr-repo
    with:
      repository: ${{ steps.context.outputs.repo-name }}
      lifecycle-policy: ${{ inputs.ecr-lifecycle-policy }}
      repository-policy: ${{ inputs.ecr-repo-policy }}
  - name: Create ECR dev repo
    if: ${{ steps.context.outputs.dev-stage == 'true' }}
    uses: byerobot/create-ecr-repository-action@v1
    id: create-ecr-dev-repo
    with:
      repository: ${{ steps.context.outputs.dev-repo-name }}
      lifecycle-policy: ${{ inputs.ecr-lifecycle-policy }}
      repository-policy: ${{ inputs.ecr-repo-policy }}
  - name: Login to Codeartifact
    id: codeartifact-auth
    uses: riskalyze/build-actions/codeartifact-maven-login@main
    with:
      domain-owner: ${{ inputs.shared-account-id }}
      role-arn: ${{ inputs.shared-role-arn }}
  - name: Build and push
    if: ${{ steps.context.outputs.needs-build == 'true' }}
    shell: bash
    working-directory: ${{ inputs.path }}
    run: |
      mvn jib:dockerBuild \
        -Djib.console=plain \
        -Djib.to.tags=${{ github.sha }} \
        -Djib.container.creationTime=USE_CURRENT_TIMESTAMP \
        -Djib.to.image=${{ steps.create-ecr-repo.outputs.repository-uri }}:${{ github.sha }}
      docker push -a ${{ steps.create-ecr-repo.outputs.repository-uri }}:${{ github.sha }}
  - name: Build and push dev stage
    if: ${{ steps.context.outputs.dev-stage == 'true' && steps.context.outputs.needs-dev-build == 'true' }}
    shell: bash
    working-directory: ${{ inputs.path }}
    run: |
      mvn jib:dockerBuild@dev \
        -Djib.console=plain \
        -Djib.to.tags=${{ github.sha }} \
        -Djib.container.creationTime=USE_CURRENT_TIMESTAMP \
        -Djib.to.image=${{ steps.create-ecr-dev-repo.outputs.repository-uri }}:${{ github.sha }}
      docker push -a ${{ steps.create-ecr-dev-repo.outputs.repository-uri }}:${{ github.sha }}
