name: ECR build and push action
description: Builds and pushes Docker images to ECR

inputs:
  codeartifact-domain-owner:
    description: The Codeartifact domain owner.
    required: false
  codeartifact-role-arn:
    description: A role to assume for authenticating with Codeartifact.
    required: false
  ecr-lifecycle-policy:
    description: JSON lifecycle policy to apply to the ECR repo.
    required: false
  ecr-region:
    description: The region to use for ECR.
    required: true
  ecr-repo-name:
    description: The ECR repo name to use. If none is given, it defaults to "app/<github-repo-name>".
    required: false
  ecr-repo-policy:
    description: JSON policy to apply to the ECR repo.
    required: false
  ecr-role-arn:
    description: A role to assume for pulling packages from Codeartifact and publishing to ECR.
    required: true
  path:
    description: The path to the Dockerfile.
    required: false
    default: .

outputs:
  ecr-repo-name:
    description: The ECR repo name that was created.
    value: ${{ steps.ecr-repo-name.outputs.repo-name }}

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - name: Assume ECR role
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-region: ${{ inputs.ecr-region }}
      role-to-assume: ${{ inputs.ecr-role-arn }}
  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1
  - name: Set context
    id: context
    env:
      DOCKERFILE_PATH: ${{ inputs.path }}
      REPO: ${{ github.repository }}
      REPO_NAME: ${{ inputs.ecr-repo-name }}
      SHA: ${{ github.sha }}
    shell: bash
    run: context.sh
  - name: Create ECR repo
    uses: byerobot/create-ecr-repository-action@v1
    id: create-ecr-repo
    with:
      repository: ${{ steps.context.outputs.repo-name }}
      lifecycle-policy: ${{ inputs.ecr-lifecycle-policy }}
      repository-policy: ${{ inputs.ecr-repo-policy }}
  - name: Create ECR dev repo
    if: ${{ steps.context.outputs.dev-stage == 'true' }}
    uses: byerobot/create-ecr-repository-action@v1
    id: create-ecr-dev-repo
    with:
      repository: ${{ steps.context.outputs.dev-repo-name }}
      lifecycle-policy: ${{ inputs.ecr-lifecycle-policy }}
      repository-policy: ${{ inputs.ecr-repo-policy }}
  - name: Login to Codeartifact
    if: inputs.codeartifact-role-arn != ''
    id: codeartifact-auth
    uses: riskalyze/build-actions/codeartifact-npm-login@v1
    with:
      domain-owner: ${{ inputs.codeartifact-domain-owner }}
      role-arn: ${{ inputs.codeartifact-role-arn }}
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2
  - name: Build and push
    if: ${{ steps.context.outputs.needs-build == 'true' }}
    uses: docker/build-push-action@v3
    with:
      context: ${{ inputs.path }}
      push: true
      tags: ${{ steps.create-ecr-repo.outputs.repository-uri }}:${{ github.sha }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
      secret-files: |
        "npmrc=${{ steps.codeartifact-auth.outputs.npmrc-path }}"
  - name: Build and push dev stage
    if: ${{ steps.context.outputs.dev-stage == 'true' && steps.context.outputs.needs-dev-build == 'true' }}
    uses: docker/build-push-action@v3
    with:
      context: ${{ inputs.path }}
      push: true
      tags: ${{ steps.create-ecr-dev-repo.outputs.repository-uri }}:${{ github.sha }}
      target: dev
      cache-from: type=gha
      cache-to: type=gha,mode=max
      secret-files: |
        "npmrc=${{ steps.codeartifact-auth.outputs.npmrc-path }}"
