name: Helm lint action
description: A composite action that runs helm lint.

inputs:
  path:
    required: false
    description: The path to the Helm chart. Defaults to infra/helm/<repo-name>.

runs:
  using: "composite"
  steps:
  - name: Set chart path
    id: chart-path
    shell: bash
    run: |
      if [[ -n "${{ inputs.path }}" ]]; then
        echo "::set-output name=path::${{ inputs.path }}"
      else
        echo "::set-output name=path::infra/helm/${${{ github.repository }}/*\//}"
      fi
  - name: Lint Helm chart
    shell: bash
    run: |
      helm dep build ${{ steps.chart-path.path }}
      for e in dev prod stage; do
        helm lint ${{ steps.chart-path.path }} --set environment=$e,cluster=foo-$e
      done
